functionality:
  name: filter_vars
  namespace: process_dataset
  info:
    type: process_dataset
    type_info:
      label: Filter variables
      summary: Remove low-quality variables from the dataset
      description: |
        This task removes low-quality variables from the dataset.
  arguments:
    - name: --input
      type: file
      required: true
      direction: input
      example: resources/neurips-2023-raw/pseudobulk.h5ad
    - name: --output
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/pseudobulk_cleaned.h5ad
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
    setup:
      - type: r
        cran: [ edgeR, limma, dplyr, tidyr, purrr, tibble ]
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
