functionality:
  name: convert_kaggle_h5ad_to_parquet
  namespace: task/process_dataset
  info:
    type: process_dataset
    type_info:
      label: H5AD to Parquet
      summary: Convert Kaggle h5ad to parquet
      description: |
        Convert dataset from h5ad files into training and test parquet files.
  argument_groups:
    - name: Inputs
      arguments:
      - name: --input_train
        type: file
        required: true
        direction: input
        example: resources/neurips-2023-kaggle/12_de_by_cell_type_train.h5ad
      - name: --input_test
        type: file
        required: true
        direction: input
        example: resources/neurips-2023-kaggle/12_de_by_cell_type_test.h5ad
      - name: --input_single_cell_h5ad
        type: file
        required: true
        direction: input
        example: resources/neurips-2023-raw/sc_counts.h5ad
    - name: Metadata
      arguments:
        - name: "--dataset_id"
          type: string
          description: Unique identifier of the dataset.
          required: true
        - name: "--dataset_name"
          type: string
          description: Nicely formatted name.
          required: true
        - name: "--dataset_url"
          type: string
          description: Link to the original source of the dataset.
          required: false
        - name: "--dataset_reference"
          type: string
          description: Bibtex reference of the paper in which the dataset was published.
          required: false
        - name: "--dataset_summary"
          type: string
          description: Short description of the dataset.
          required: true
        - name: "--dataset_description"
          type: string
          description: Long description of the dataset.
          required: true
        - name: "--dataset_organism"
          type: string
          description: The organism of the dataset.
          required: true
    - name: Outputs
      arguments:
        - name: --output_train_h5ad
          type: file
          required: true
          direction: output
          example: resources/neurips-2023-kaggle/de_train.h5ad
        - name: --output_test_h5ad
          type: file
          required: true
          direction: output
          example: resources/neurips-2023-kaggle/de_test.h5ad
        - name: --output_id_map
          type: file
          required: true
          direction: output
          example: resources/neurips-2023-kaggle/id_map.csv
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ fastparquet, anndata, pandas ]
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
