functionality:
  name: "add_uns_metadata"
  namespace: "process_dataset"
  version: "1.0.0"
  arguments:
  - type: "file"
    name: "--input"
    info: null
    example:
    - "resources/neurips-2023-raw/pseudobulk_cleaned.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_id"
    description: "Unique identifier of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_name"
    description: "Nicely formatted name."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_url"
    description: "Link to the original source of the dataset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_reference"
    description: "Bibtex reference of the paper in which the dataset was published."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_summary"
    description: "Short description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_description"
    description: "Long description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_organism"
    description: "The organism of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    info: null
    example:
    - "resources/neurips-2023-data/pseudobulk_uns.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  info:
    type: "process_dataset"
    type_info:
      label: "Add metadata"
      summary: "Add metadata to the pseudobulked data"
      description: "Add metadata to the pseudobulked single-cell dataset for the perturbation\
        \ regression task.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.4"
  target_organization: "openproblems-bio/task_perturbation_prediction"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task_perturbation_prediction"
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/src/process_dataset/add_uns_metadata/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/nextflow/process_dataset/add_uns_metadata"
  executable: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/nextflow/process_dataset/add_uns_metadata/add_uns_metadata"
  viash_version: "0.8.6"
  git_commit: "a623d3ad92e82dc099ecaf024de153237d275931"
  git_remote: "https://github.com/openproblems-bio/task_perturbation_prediction"
