functionality:
  name: "mean_across_compounds"
  namespace: "control_methods"
  version: "1.0.0"
  arguments:
  - type: "file"
    name: "--de_train_h5ad"
    info:
      label: "DE train"
      summary: "Differential expression results for training."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "sm_name"
          type: "string"
          description: "The primary name for the (parent) compound (in a standardized\
            \ representation)\nas chosen by LINCS. This is provided to map the data\
            \ in this experiment to \nthe LINCS Connectivity Map data.\n"
          required: true
        - name: "sm_lincs_id"
          type: "string"
          description: "The global LINCS ID (parent) compound (in a standardized representation).\n\
            This is provided to map the data in this experiment to the LINCS Connectivity\n\
            Map data.\n"
          required: true
        - name: "SMILES"
          type: "string"
          description: "Simplified molecular-input line-entry system (SMILES) representations\
            \ of the\ncompounds used in the experiment. This is a 1D representation\
            \ of molecular\nstructure. These SMILES are provided by Cellarity based\
            \ on the specific\ncompounds ordered for this experiment.\n"
          required: true
        - name: "split"
          type: "string"
          description: "Split. Must be one of 'control', 'train', 'public_test', or\
            \ 'private_test'"
          required: true
        - name: "control"
          type: "boolean"
          description: "Boolean indicating whether this instance was used as a control."
          required: true
        layers:
        - name: "logFC"
          type: "double"
          description: "Log fold change of the differential expression test"
          required: true
        - name: "AveExpr"
          type: "double"
          description: "Average expression of the differential expression test"
          required: false
        - name: "t"
          type: "double"
          description: "T-statistic of the differential expression test"
          required: false
        - name: "P.Value"
          type: "double"
          description: "P-value of the differential expression test"
          required: true
        - name: "adj.P.Value"
          type: "double"
          description: "Adjusted P-value of the differential expression test"
          required: true
        - name: "B"
          type: "double"
          description: "B-statistic of the differential expression test"
          required: false
        - name: "is_de"
          type: "boolean"
          description: "Whether the gene is differentially expressed"
          required: true
        - name: "is_de_adj"
          type: "boolean"
          description: "Whether the gene is differentially expressed after adjustment"
          required: true
        - name: "sign_log10_pval"
          type: "double"
          description: "Differential expression value (`-log10(p-value) * sign(LFC)`)\
            \ for each gene.\nHere, LFC is the estimated log-fold change in expression\
            \ between the treatment\nand control condition after shrinkage as calculated\
            \ by Limma. Positive LFC means\nthe gene goes up in the treatment condition\
            \ relative to the control.\n"
          required: true
        - name: "clipped_sign_log10_pval"
          type: "double"
          description: "A clipped version of the sign_log10_pval layer. Values are\
            \ clipped to be between\n-4 and 4 (i.e. `-log10(0.0001)` and `-log10(0.0001)`).\n"
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - name: "dataset_name"
          type: "string"
          description: "A human-readable name for the dataset."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
          multiple: true
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
          multiple: true
        - name: "single_cell_obs"
          type: "dataframe"
          description: "A dataframe with the cell-level metadata for the training\
            \ set.\n"
          required: true
    example:
    - "resources/neurips-2023-data/de_train.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--de_test_h5ad"
    info:
      label: "DE test"
      summary: "Differential expression results for testing."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "sm_name"
          type: "string"
          description: "The primary name for the (parent) compound (in a standardized\
            \ representation)\nas chosen by LINCS. This is provided to map the data\
            \ in this experiment to \nthe LINCS Connectivity Map data.\n"
          required: true
        - name: "sm_lincs_id"
          type: "string"
          description: "The global LINCS ID (parent) compound (in a standardized representation).\n\
            This is provided to map the data in this experiment to the LINCS Connectivity\n\
            Map data.\n"
          required: true
        - name: "SMILES"
          type: "string"
          description: "Simplified molecular-input line-entry system (SMILES) representations\
            \ of the\ncompounds used in the experiment. This is a 1D representation\
            \ of molecular\nstructure. These SMILES are provided by Cellarity based\
            \ on the specific\ncompounds ordered for this experiment.\n"
          required: true
        - name: "split"
          type: "string"
          description: "Split. Must be one of 'control', 'train', 'public_test', or\
            \ 'private_test'"
          required: true
        - name: "control"
          type: "boolean"
          description: "Boolean indicating whether this instance was used as a control."
          required: true
        layers:
        - name: "logFC"
          type: "double"
          description: "Log fold change of the differential expression test"
          required: true
        - name: "AveExpr"
          type: "double"
          description: "Average expression of the differential expression test"
          required: false
        - name: "t"
          type: "double"
          description: "T-statistic of the differential expression test"
          required: false
        - name: "P.Value"
          type: "double"
          description: "P-value of the differential expression test"
          required: true
        - name: "adj.P.Value"
          type: "double"
          description: "Adjusted P-value of the differential expression test"
          required: true
        - name: "B"
          type: "double"
          description: "B-statistic of the differential expression test"
          required: false
        - name: "is_de"
          type: "boolean"
          description: "Whether the gene is differentially expressed"
          required: true
        - name: "is_de_adj"
          type: "boolean"
          description: "Whether the gene is differentially expressed after adjustment"
          required: true
        - name: "sign_log10_pval"
          type: "double"
          description: "Differential expression value (`-log10(p-value) * sign(LFC)`)\
            \ for each gene.\nHere, LFC is the estimated log-fold change in expression\
            \ between the treatment\nand control condition after shrinkage as calculated\
            \ by Limma. Positive LFC means\nthe gene goes up in the treatment condition\
            \ relative to the control.\n"
          required: true
        - name: "clipped_sign_log10_pval"
          type: "double"
          description: "A clipped version of the sign_log10_pval layer. Values are\
            \ clipped to be between\n-4 and 4 (i.e. `-log10(0.0001)` and `-log10(0.0001)`).\n"
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - name: "dataset_name"
          type: "string"
          description: "A human-readable name for the dataset."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
          multiple: true
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
          multiple: true
        - name: "single_cell_obs"
          type: "dataframe"
          description: "A dataframe with the cell-level metadata.\n"
          required: true
    example:
    - "resources/neurips-2023-data/de_test.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--id_map"
    info:
      label: "ID Map"
      summary: "File indicates the order of de_test, the cell types and the small\
        \ molecule names."
      file_type: "csv"
      columns:
      - name: "id"
        type: "integer"
        description: "Index of the test observation"
        required: true
      - name: "cell_type"
        type: "string"
        description: "Cell type name"
        required: true
      - name: "sm_name"
        type: "string"
        description: "Small molecule name"
        required: true
    example:
    - "resources/neurips-2023-data/id_map.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--layer"
    description: "Which layer to use for prediction."
    info: null
    default:
    - "clipped_sign_log10_pval"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    info:
      label: "Prediction"
      summary: "Differential Gene Expression prediction"
      file_type: "h5ad"
      slots:
        layers:
        - name: "prediction"
          type: "double"
          description: "Predicted differential gene expression"
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method used to generate the prediction."
          required: true
    example:
    - "resources/neurips-2023-data/prediction.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "../../utils/anndata_to_dataframe.py"
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources/neurips-2023-data"
    dest: "resources/neurips-2023-data"
  info:
    label: "Mean per compound and gene"
    summary: "Baseline method that returns mean of compound's outcomes"
    description: "Baseline method that predicts for a compound the mean of its outcomes\
      \ of all samples.\n"
    type: "control_method"
    type_info:
      label: "Control Method"
      summary: "A control method."
      description: "A control method to serve as a quality control for the perturbation\
        \ prediction benchmark.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.4"
  target_organization: "openproblems-bio/task_perturbation_prediction"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task_perturbation_prediction"
  setup:
  - type: "python"
    user: false
    packages:
    - "fastparquet"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/src/control_methods/mean_across_compounds/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/nextflow/control_methods/mean_across_compounds"
  executable: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/nextflow/control_methods/mean_across_compounds/mean_across_compounds"
  viash_version: "0.8.6"
  git_commit: "a623d3ad92e82dc099ecaf024de153237d275931"
  git_remote: "https://github.com/openproblems-bio/task_perturbation_prediction"
