functionality:
  name: compute_pseudobulk
  namespace: process_dataset
  info:
    type: process_dataset
    type_info:
      label: Pseudobulk
      summary: Compute pseudobulk data
      description: |
        Compute pseudobulk data for the DGE regression task.
  arguments:
    - name: --input
      type: file
      required: true
      direction: input
      example: resources/neurips-2023-data/sc_counts_cleaned.h5ad
    - name: --output
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/pseudobulk.h5ad
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    setup:
      - type: python
        packages: [ pyarrow ]
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
