functionality:
  name: clean_sc_counts
  namespace: process_dataset
  info:
    type: process_dataset
    type_info:
      label: Clean dataset
      summary: Clean up the single-cell dataset
      description: |
        Clean up the single-cell dataset for the DGE regression task.
  arguments:
    - name: --input
      type: file
      required: true
      direction: input
      example: resources/neurips-2023-raw/sc_counts.h5ad
    - name: --lincs_id_compound_mapping
      type: file
      required: true
      direction: input
      example: resources/neurips-2023-raw/lincs_id_compound_mapping.parquet
    - name: --output
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/sc_counts_cleaned.h5ad
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    setup:
      - type: python
        packages: [ pyarrow ]
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
