__merge__: ../../api/comp_method.yaml
functionality:
  name: random_forest
  info:
    label: Random Forests
    summary: Random forest regression.
    description: A random forest regression method.
    reference: breiman2001random
    documentation_url: https://www.stat.berkeley.edu/~breiman/RandomForests/reg_home.htm
    repository_url: https://github.com/cran/randomForest
    preferred_normalization: counts
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.2
    setup:
      - type: r
        cran: [ ranger, arrow, pbapply ]
      - type: python
        packages: [ fastparquet ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]