functionality:
  name: "filter_obs"
  namespace: "process_dataset"
  version: "1.0.0"
  arguments:
  - type: "file"
    name: "--input"
    info: null
    example:
    - "resources/neurips-2023-raw/sc_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    info: null
    example:
    - "resources/neurips-2023-data/sc_counts_cleaned.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "r_script"
    path: "script.R"
    is_executable: true
  info:
    type: "process_dataset"
    type_info:
      label: "Filter observations"
      summary: "Remove low-quality observations from the dataset"
      description: "This task removes low-quality observations from the dataset.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_r:1.0.4"
  target_organization: "openproblems-bio/task_perturbation_prediction"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task_perturbation_prediction"
  setup:
  - type: "r"
    cran:
    - "dplyr"
    - "tidyr"
    - "purrr"
    - "tibble"
    bioc_force_install: false
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/src/process_dataset/filter_obs/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/nextflow/process_dataset/filter_obs"
  executable: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/nextflow/process_dataset/filter_obs/filter_obs"
  viash_version: "0.8.6"
  git_commit: "a623d3ad92e82dc099ecaf024de153237d275931"
  git_remote: "https://github.com/openproblems-bio/task_perturbation_prediction"
